spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/mgj?serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
  mvc:
    date-format: yyyy-MM-dd
mybatis:
  mapper-locations: classpath:mapper/*.xml
server:
  port: 8081
 